blank_lines_upper_bound = 2
combine_control_expr = false
empty_item_single_line = false
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Lower"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 90
imports_granularity = "One"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "One"
short_array_element_width_threshold = 0
spaces_around_ranges = true
tab_spaces = 2
trailing_comma = "Never"
unstable_features = true
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true
wrap_comments = true
